language: go

sudo: false

go:
 - 1.5

script:
 - make full-test

before_deploy:
  - make packages

deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
  file:
    - build/dockership_${TRAVIS_TAG}_darwin_amd64.tar.gz
    - build/dockership_${TRAVIS_TAG}_linux_amd64.tar.gz
  skip_cleanup: true
  on:
    tags: true
